[package]
name = "Gerber-To-SolderMask-STP"
version = "0.1.0"
edition = "2021"

[dependencies]
dxf = "0.5.0"
gerber-types = "0.3.0"
#gerber_parser = "0.1.2"
gerber_parser = { path = "../gerber-parser-lib" }
