[package]
name = "Gerber-To-SolderMask-DXF"
version = "0.1.0"
edition = "2021"

[dependencies]
dxf = "0.5.0"
gerber-types = "0.3.0"
#gerber_parser = "0.1.2"
gerber_parser = { git = "https://github.com/paulwrath1223/gerber-parser.git", rev = "44678d17e4979c2baf94c624d2020455f0c78c3e" }
